### ISSUE TITLE
URL de retorno

### ISSUE THREAD

**Issue by tiagocaus** [codephix/asaas-sdk#12]
Como informo a URL de retorno para receber as confirmações de pagamento dos boletos, pix e cartão?

**Comment by codephix** [comment]
Opa Thiago, precisa fazer os seguintes passos.

Minha Conta -> Integrações 

Nessa sela vai ter a opção de webhook, ai e só  informar a url onde irá tratar os retorno de confirmação de pagamento, ou qualquer alteração na cobrança

**Comment by tiagocaus** [comment]
Obrigado. Tinha enviado um atualização, pois email não é obrigatório no cadastro do cliente. Abraços.
