### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by tiagocaus** [codephix/asaas-sdk#13]
URL de retorno apresentando erro **403 Forbidden**

> IMG = https://prnt.sc/1r5z22b
> IMG = https://prnt.sc/1r5zey8

O que estou fazendo de errado? Usando o postmam consigo enviar comandos POST sem nenhum problema, até adicionei os ips como eles sugerem.

**Comment by codephix** [comment]
Eu utilizo dessa maneira, e atribuo os metodos e faço os comandos que preciso.

provavelmente está tendo algum erro na url, que não esta encontrado, ou seu Framework esta bloqueando o acesso.


1 - tenta colocar um arquivo em branco só dando um print, para exibir os dados, após isso vai aos poucos implementando as rotas e cada ação.



    $ss = file_get_contents( 'php://input' );
        
    $ss = json_decode($ss);
    
    if($ss){
    
    	switch ($ss->event) {
    		case 'PAYMENT_CREATED':
    			# code...
    			break;
    		case 'PAYMENT_UPDATED':
    			# code...
    			break;
    		case 'PAYMENT_CONFIRMED':
    		case 'PAYMENT_RECEIVED':
    			# code...
    			
    			break;
    		case 'PAYMENT_OVERDUE':
    			# code...
    			break;
    		case 'PAYMENT_DELETED':
    			# code...
    
    			break;
    		case 'PAYMENT_REFUNDED':
    			# code...
    			break;
    		case 'PAYMENT_CHARGEBACK_REQUESTED':
    			# code...
    			break;
    		case 'PAYMENT_CHARGEBACK_DISPUTE':
    			# code...
    			break;
    		case 'PAYMENT_AWAITING_CHARGEBACK_REVERSAL':
    			# code...
    			break;
    
    		default:
    			# code...
    			break;
    	}
    }

**Comment by tiagocaus** [comment]
@codephix descobrir de onde vem o problemas. Está no cloudflare, desativei geral e funcionou. Agora estou tentando criar uma regra para desativar apenas uma URL específica.
