### ISSUE TITLE
Versões não batem. Packagist e github

### ISSUE THREAD

**Issue by tiagocaus** [codephix/asaas-sdk#17]
Esse projeto parou?
No packagist, não consigo baixar a versão com PIX.

Aqui no github, mostra que tem, mas quando baixo via packagist, não vem os arquivos atualizados.

**Comment by codephix** [comment]
Opa Tiago, esses dias vou ta atualizando a versão para mais nova.

**Comment by tiagocaus** [comment]
Se eu tiver como pedir uma enorme gentileza, e também se for possível... fazer hoje?
Quero colocar essa opção em produção ainda essa semana.

Grande abraço!

**Comment by tiagocaus** [comment]
@codephix  Conseguiu atualizar o packagist?

**Comment by codephix** [comment]
Foi atualizado, desculpe a demora.

**Comment by tiagocaus** [comment]
@codephix Show!
