### ISSUE TITLE
Fatal error ao usar a classe.

### ISSUE THREAD

**Issue by luccavallari** [codephix/asaas-sdk#3]
Olá, estou tentando utilizar este sdk porém parece que existem algum problema ao tentar encontrar a classe. 

Fatal error: Uncaught Error: Class 'CodePhix\Asaas' not found

Eu testei em 2 ambientes distintos e não consegui rodar. Podem me orientar como proceder?

**Comment by codephix** [comment]
Opa Amigo para utilizar o componente precisa fazer o seguinte, pode ser dessas 2 maneiras

use \CodePhix\Asaas\Asaas;
$Asaas = new Asaas;

ou 

$Asaas = new \CodePhix\Asaas\Asaas();

Utilizo em meus projetos e todas estão funcionando;

**Comment by luccavallari** [comment]
Oi @codephix ! Muito obrigado pelo seu retorno. 

De fato utilizando da forma que coloca funciona perfeitamente. 

Sugiro atualizar esta informação no exemplo do readme.md pois lá está assim: use \CodePhix\Asaas 

Muito Obrigado!
