### ISSUE TITLE
Erro ao chamar Asaas!

### ISSUE THREAD

**Issue by willph** [codephix/asaas-sdk#30]
Gostaria de saber se a versão mais recente esta funcionado ok?

Se sim eu irei verificar o que esta acontecendo.

No meu esta dando erro ao criar o cliente em modo produção.

**Comment by willph** [comment]
> Gostaria de saber se a versão mais recente esta funcionado ok?
> 
> Se sim eu irei verificar o que esta acontecendo.
> 
> No meu esta dando erro ao criar o cliente em modo produção.

Modo SandBox e o retorno é "Erro ao chamar Asaas!"

**Comment by codephix** [comment]
Opa Amigo boa noite, para utilizar o modo sandbox precisa definir a variável na inicialização da class.  qualquer duvida pode me chamar.
