### ISSUE TITLE
Undefined array key "HTTP_USER_AGENT"

### ISSUE THREAD

**Issue by jeanalmesilva** [codephix/asaas-sdk#42]
Undefined array key "HTTP_USER_AGENT"

**Comment by jeansilvaofficial** [comment]
Conection.php linha 38 -> $_SERVER['HTTP_USER_AGENT'] ?? 'Desconhecido'
Conection.php linha 79 -> $_SERVER['HTTP_USER_AGENT'] ?? 'Desconhecido'

**Comment by jeansilvaofficial** [comment]
Alguma luz?
